services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_ENCRYPTION_KEY: "mock_encryption_key"
    volumes:
      - ./src/test/resources/n8n:/home/node/.n8n/workflows
      - ./src/test/resources/n8n/n8n_init.sh:/home/node/n8n_init.sh
    entrypoint: ["/bin/sh", "/home/node/n8n_init.sh"]